apiVersion: storage.k8s.io/v1 
kind: StorageClass 
metadata:
  name: ceph-rbd
  annotations: {"storageclass.kubernetes.io/is-default-class":"true"} 
provisioner: kubernetes.io/rbd 
parameters:
  monitors: ip-10-0-206-88:6789,ip-10-0-85-206:6789,ip-10-0-138-207:6789
  pool: kube
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: "kube-system"
  userId: kube
  userSecretName: ceph-secret-kube
  fsType: ext4
  imageFormat: "2"
  imageFeatures: "layering"
