apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment1
  labels:
    app: nginx1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
#      containers:
#      - name: nginx1
#        image: nginx:1.15.4
#        ports:
#        - containerPort: 80
      volumes:
        - name: test-pvc-storage
          persistentVolumeClaim:
            claimName: claim1
      containers:
        - name: test-container
          image: nginx:alpine
          volumeMounts:
            - name: test-pvc-storage
              mountPath: /usr/share/nginx/html/
          ports:
          - containerPort: 80
